services:
  dt-core:
    container_name: dt-core
    image: harbor.distributedtesting.org/dot-ostr-dt/dt-core:wrangler
    profiles: ["core"]
    tty: true
    ipc: "host"
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=~/.Xauthority
      - VUG_CONTAINER_IMAGE=dt-core
      - VUG_SITE_CONFIG_FILE=${VUG_SITE_CONFIG_FILE}
      - VUG_SCENARIO_CONFIG_FILE=${VUG_SCENARIO_CONFIG_FILE}
      - VUG_VPN_LOCAL_ADDRESS=${VUG_VPN_LOCAL_ADDRESS}
      - VUG_VPN_EM_ADDRESS=${VUG_VPN_EM_ADDRESS}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${VUG_LOCAL_DT_PATH}:/home/dt_user/distributed-testing
    stop_grace_period: 30s

  dt-carla:
    container_name: dt-carla
    image: harbor.distributedtesting.org/dot-ostr-dt/dt-carla:0-9-15-0.0.6
    profiles: ["carla"]
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=~/.Xauthority
      - VUG_CONTAINER_IMAGE=dt-carla
      - VUG_SITE_CONFIG_FILE=${VUG_SITE_CONFIG_FILE}
      - VUG_SCENARIO_CONFIG_FILE=${VUG_SCENARIO_CONFIG_FILE}
      - VUG_VPN_LOCAL_ADDRESS=${VUG_VPN_LOCAL_ADDRESS}
      - VUG_VPN_EM_ADDRESS=${VUG_VPN_EM_ADDRESS}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${VUG_LOCAL_DT_PATH}:/home/carla/distributed-testing
    stop_grace_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  dt-simdis:
    container_name: dt-simdis
    image: harbor.distributedtesting.org/dot-ostr-dt/dt-simdis:wrangler
    profiles: ["simdis"]
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=~/.Xauthority
      - VUG_CONTAINER_IMAGE=dt-simdis
      - VUG_SITE_CONFIG_FILE=${VUG_SITE_CONFIG_FILE}
      - VUG_SCENARIO_CONFIG_FILE=${VUG_SCENARIO_CONFIG_FILE}
      - VUG_VPN_LOCAL_ADDRESS=${VUG_VPN_LOCAL_ADDRESS}
      - VUG_VPN_EM_ADDRESS=${VUG_VPN_EM_ADDRESS}
      - SIMDIS_DIR=/home/dt_user/SIMDIS
      - SIMDIS_DISCN_FILE=/home/dt_user/distributed-testing/SIMDIS_Files/POC-X.discn
      - SIMDIS_LAYOUT=/home/dt_user/distributed-testing/SIMDIS_Files/layout.ini
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${VUG_LOCAL_DT_PATH}:/home/dt_user/distributed-testing
      - /home/dev/SIMDIS_Files:/home/dt_user/distributed-testing/SIMDIS_Files
    stop_grace_period: 30s
    command: ["/bin/bash","-l","-c","cd /home/dt_user/SIMDIS && ./startSIMDIS.sh --maximized --discn $${SIMDIS_DISCN_FILE} -l $${SIMDIS_LAYOUT}"]
    # Enable on systems with NVIDIA GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
