services:
  dt-carla:
    container_name: dt-carla
    image: harbor.distributedtesting.org/distributed-testing/dt-carla:0.10.0
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=~/.Xauthority
      - VUG_CONTAINER_IMAGE=dt-carla
      - VUG_SITE_CONFIG_FILE=${VUG_SITE_CONFIG_FILE}
      - VUG_SCENARIO_CONFIG_FILE=${VUG_SCENARIO_CONFIG_FILE}
      - VUG_VPN_LOCAL_ADDRESS=${VUG_VPN_LOCAL_ADDRESS}
      - VUG_VPN_EM_ADDRESS=${VUG_VPN_EM_ADDRESS}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${VUG_LOCAL_DT_PATH}:/home/carla/distributed-testing
    stop_grace_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]