services:
  carla-voices:
    container_name: carla-voices
    image: usdotfhwastoldev/carla-voices:pilot2-event0-latest
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=~/.Xauthority
      - VUG_CONTAINER_IMAGE=carla-voices
      - VUG_SITE_CONFIG_FILE=${VUG_SITE_CONFIG_FILE}
      - VUG_SCENARIO_CONFIG_FILE=${VUG_SCENARIO_CONFIG_FILE}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${VUG_LOCAL_VOICES_POC_PATH}:/home/carla/voices-poc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  voices:
    container_name: voices
    image: usdotfhwastoldev/voices:pilot2-event0-latest
    tty: true 
    depends_on:
      - carla-voices
    network_mode: "host"
    ipc: "host"
    environment:
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=~/.Xauthority
      - VUG_CONTAINER_IMAGE=voices
      - VUG_SITE_CONFIG_FILE=${VUG_SITE_CONFIG_FILE}
      - VUG_SCENARIO_CONFIG_FILE=${VUG_SCENARIO_CONFIG_FILE}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${VUG_LOCAL_VOICES_POC_PATH}:/home/voices-poc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]